language: generic
sudo: required
services: 
    - docker

before_install:
    - docker build -t zapp03/docker-test -f Dockerfile.dev .

script:
    - docker run -e CI=true zapp03/docker-test npm run test

deploy:
    provider: elasticbeanstalk
    region: "us-east-2"
    app: "docker-test"
    env: "DockerTest-env"
    bucket_name: "elasticbeanstalk-us-east-2-217388062771"
    bucket_path: "docker-test"
    on: 
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY